### ISSUE TITLE
Mining pool functionality?

### ISSUE THREAD

**Issue by doffing81** [ignopeverell/grin#193]
Seeing as how mining itself is not only important, but also part of the reference client, shouldn’t the ability to create and/or connect to pools be in the reference client as well?  Such functionality seems like it could have great potential for decentralization?

**Comment by gazhayes** [comment]
Mining pools will show up naturally, and so will (more efficient) mining software, no need to build it into the client.

**Comment by ignopeverell** [comment]
Exactly. Just said differently, we need some mining ability in the reference software to be able to test and debug (bitcoind does too btw). It also turns out that @yeastplume has done an excellent job at making a well-optimized miner that would be easy to integrate with a pool client. The rest is left as an exercise to the reader :-)

That being said, I'm not sure decentralized and mining pool fit in the same sentence. It'd be great to be solo-mining friendly and Cuckoo Cycle does a great job there, but mining pools are hard to avoid with proof of work. I would love to see good p2pool implementation if someone want to step up.

**Comment by doffing81** [comment]
Definitely unnecessary.  Guess I just like the idea for ease.  I picture helping non-technical friends set up nodes, and easily creating a pool amongst acquaintances, since as you say, it is more solo-mining friendly, whereby, I guess, it is this little idea of easily created, smaller pools, that I am referencing with respect to decentralization, which of course may not be correctly characterized as such.  No doubt such a feature would be just that, a feature, and I’m certain there is much more to be concerned with.  I merely thought it was worthy of consideration.
