### ISSUE TITLE
Ouput and input commitments are reversed in mod.rs

### ISSUE THREAD

**Issue by melaurent** [ignopeverell/grin#37]
at https://github.com/ignopeverell/grin/blob/afb219ce5c6bf5adb21e638df96a2b3b66cd2e24/core/src/core/mod.rs#L66
it should be `secp.commit_sum(output_commits, input_commits)` , otherwise, the resulting sum  corresponds to -kG instead of kG

**Comment by ignopeverell** [comment]
As long as it's consistent it doesn't really matter. Signs make sense in algebra but aren't equivalent when translated to elliptic curve points. In the code I chose to follow the Jedusor paper, where one takes the r-value of change minus inputs and outputs are added afterward. Makes sense?

**Comment by melaurent** [comment]
I'm not quite sure I understand. In the code, the signature of commit_sum is:
`pub fn commit_sum(&sef,
                                   positive: Vec<Commitment>,
                                   negative: Vec<Commitment>)
                                   -> Result<Commitment, Error>`
So it is going to do `inputs - outputs` of the transaction we want to verify, which will give the key `(x, -y)` if the key `kG` is `(x, y)`. You can try inverting it, the `y` of the public key changes depending on the order of the arguments. Sorry if I'm missing something here

**Comment by ignopeverell** [comment]
You're right, for some reason I read that line `secp.commit_sum(output_commits, input_commits)` instead of what it actually was (`secp.commit_sum(output_commits, input_commits)`). I must have been looking at it too late.

I'm about to push a fix to invert everything. As I said it doesn't really matter as far as validity is concerned but it will be more consistent with the literature.
