### ISSUE TITLE
Delegate Serialization Format to Grin-Store 

### ISSUE THREAD

**Issue by Latrasis** [ignopeverell/grin#39]
(In collaboration with @trhode)

Currently every stored type is responsible for providing it's own encoding and decoding format via the `core::ser::{Writable, Readable}`. It seems more efficient to delegate the encoding and decoding format to one generic [Serializer](https://docs.serde.rs/serde/ser/trait.Serializer.html)/[Deserializer](https://docs.serde.rs/serde/de/trait.Deserializer.html) ( bincode, json, etc...).

It seems as though the need for the`Readable`/`Writable` traits in the Grin-core stemmed from the inability to implement `Serializable` for the `secp256k1` types. If so implementing `Serializable` in secp256k1 seems like a good place to start.

Removing the Readable/Writable traits would simplify the codebase greatly, which is one of the stated goals of the grin-core project.

**Comment by ignopeverell** [comment]
There are multiple elements to consider that motivated the decision of doing a custom serialization layer. I'll list them below. I'm open to to revisiting this decision, as you mention there's quite a bit of serialization code that I wish we could get rid off. I wouldn't confuse simplicity for brevity though. Relying on another serialization library could improve brevity, it may or may not improve simplicity.

* Serialization is consensus-critical. Offloading it to a downstream library increases risk of consensus failure due to downstream upgrades.
* Protocol changes are harder to keep backward-compatible with non-custom code. It's also harder to include information that helps future backward-compatibility. For example say you just want to add a u32 for the length of multiple fields that follow. Some peers may ignore these fields, others may not. Doing this without custom serialization is more complex and sometimes require an additional layer of structs, just to prepare for serialization. It becomes ugly quickly.
* Serialization is also the public interface of a peer. Another peer implemented in Go or node.js for example (which I'd love to see eventually btw) shouldn't have to bend backward due to Rust-specific (or Rust-library specific) encodings (like bincode). People also learn to read the serialized representation (many bitcoin developers can read a serialized transaction directly from its hex encoding for example).
* Given the above, there are advantages in having the serialization code in the same codebase. It's easier for people to find and refer to. The resulting code is easier to understand as you don't have to know the details of the libraries being used.
* Along the same lines, serde custom serializers and deserializers (especially the latter) can be difficult to read and reason about. It's a much thicker abstraction layer. I think the current serialization succeeds (although could definitely be improved further) at being a very thin and straightforward abstraction.
* Compactness can be a concern. Generally it's a fairly minor one, but many of the more standard binary encodings include fields, which is a problem for us.

There are many codebases for which serialization is an implementation detail. For grin/mw and most public blockchains however, the serialization layer is a leaky abstraction.

I did fall down the rabbit hole of looking at many different serialization solutions, including serde and capt'n proto. Because of all the considerations above, I decided against. But I'm more than happy to hear arguments that add weigh on the serde side of the scale.

**Comment by Latrasis** [comment]
Thank you for the thorough response. From your points, I realize that this isn't generic serialization but really encoding specific types. If this is encoding, it would make sense to have it custom for transport. 

Would it present any benifits to have the storage layer be encoding agnostic or should it just use the same format as the wire layer?

**Comment by ignopeverell** [comment]
This is a trick question :) Right now, same format as the wire layer is fine but it's unlikely to remain true. On the other hand, the longer we manage to keep them the same, the better.

The reason they could diverge is if the local node adds data to what's received over the network (a simple example would be the receive time for a block). I think we can consider that more as metadata going forward and store it separately from the raw network block.

**Comment by Latrasis** [comment]
I see. I does feels like to me that it is an anti-pattern to delegate the encoding format to the types themselves and that the encoding should be delegated to the encoder instead.

**Comment by ignopeverell** [comment]
Right, in my previous message this rings a little more dubious now: "On the other hand, the longer we manage to keep them the same, the better.". I have nothing against delegating that to an encoder instead. Actually it will likely improve modularity.

**Comment by Latrasis** [comment]
Would you prefer the encoder as seperate crate, or be part of the `grin-store` or `grin-p2p` crates instead?

**Comment by ignopeverell** [comment]
Let's go with grin-store for now.

**Comment by Latrasis** [comment]
Alright, I'll setup a pull-request for monitoring. 👍

**Comment by Latrasis** [comment]
Here it is #44

**Comment by Latrasis** [comment]
@ignopeverell: For `PeerData` i'm assuming you want to implement a codec in `grin-p2p`?

**Comment by Latrasis** [comment]
Looking over `grin-chain`, since we have a `ChainKVStore`, I'm starting to have seconds thoughts on having `grin-store` delegate type encoding. Should we just have `grin-store` accept a codec instead, and have codecs defined by dependents? The signature could look like this:


```rust

impl Store {
     //...
     pub fn put_enc<E: Encoder>(&self, encoder: &E, key: &[u8], value: &E::Item) -> Result<(), Error>;
     pub fn get_dec<D: Decoder>(&self, decoder: &D, key: &[u8]) -> Result<Option<D::Item>, D::Error>
}

```

**Comment by Latrasis** [comment]
We could also make `Store` generic by codec. Such as:
```rust
struct Store<Codec: Encoder + Decoder, Hasher: Encoder> {
    //...
    codec: Codec,
    hasher: Hasher,
}
```

**Comment by ignopeverell** [comment]
Yes, that seems reasonable to me as well.

**Comment by Latrasis** [comment]
Hi @ignopeverell, after several days working on #53 to my own dismay I'm starting to realize that it's become an uphill battle. I've been thinking about this and have started having doubts on the codec transition in general. Notably:

* Every codec has almost the exact same signatures, meaning it's just another form of Serialization.
* Encoding and Encoding for Hashing required separate Codecs, however this leads to a lot of redundancies.
* Both the `p2p` and `store` require separate encoding for each type - which required creating a generic codec, which contradicts the whole point of what a codec is for - encoding and decoding a single specific frame type.
* Separating the types for encoding in separate codec groups has become redundant and arbitrary, leading to several 'codecs' relying on other 'codecs' for encoding, which only produces additional complexity.

Let me know what you think, while I'm saddened I didn't see this earlier, I don't want to provide 'contributions' that would only hold back your progress so far.

**Comment by ignopeverell** [comment]
I'm saddened as well, it's always disheartening to spend a fair amount of time and hit a potential dead end. Having worked on the codecs for a while and knowing well the existing serialization, what do you think would be the best solution overall? What do you see as the best path going forward?

I really hope this doesn't discourage you in contributing to Grin, I've been enjoying your work a lot.

**Comment by Latrasis** [comment]
Hi @ignopeverell, looking at this overall there are two options: salvage and re-implement `Writeable`/`Readable` into `Encode`/`Decode` or to simply revert. 

As painful as it sounds, I think the best move forward is the latter, simply because the cost-benefit of the salvaging leads to questionable improvement at this point. There _might_ be some performance benefits in the long run, but in the short term it would only stall progress.

**Comment by Latrasis** [comment]
I'm still very much invested in contributing to Grin. I also very much enjoy contributing to your project. My primary concern is that my contributions do not stall your work and everybody's progress.

**Comment by ignopeverell** [comment]
@Latrasis sounds good, let's just revert then. Sorry it ends up that way. I'll close the current pull request. Do you want to open another for the revert of the previous one, or should I just commit a revert?

I like your IntoHash trait, seems more idiomatic. I'd also love to have your eyes on the p2p code, it's mostly based on tokio-core which is a moving target, but I'm not entirely happy with how it is. That being said I've spent entirely too much time on it already and wasn't able to leverage tokio-proto for a p2p protocol.

**Comment by Latrasis** [comment]
Let's just commit the revert, sounds easier.

I also agree that p2p needs to be worked on as well. I think we should open a seperate issue on it, and discuss in more detail. Looking at other implementations would help, parity seems to be using `nanomsg` for it's [transport](https://github.com/paritytech/parity/blob/master/ipc/nano/src/lib.rs) which might be worth to look at. I'll see if I can reach out to @debris or someone in the paritytech team.
