### ISSUE TITLE
Testnet genesis block

### ISSUE THREAD

**Issue by pinkvoid** [ignopeverell/grin#94]
Hi,
how to decrease difficulty of the genesis block for quick testnet testing?

Or any way to preseed with test genesis block instead of generating one?

Thanks
pinkvoid

**Comment by yeastplume** [comment]
If you just build and run via cargo from the project root (/grin) using:

`RUST_LOG=grin=debug cargo run`

It should pick up defaults from the grin.toml file, which will start in user testing mode. You can also set:

`mining_parameter_mode = "AutomatedTesting"`

If you want a really fast growing blockchain.

Alternatively, you can copy the config file into the current directory and the values in there will be picked up if you run grin without specifying any parameters on the command line.

**Comment by pinkvoid** [comment]
Thanks yeastplume I'll give it a try because the user testing mode is too slow to generate a block on my machine in a reasonable amount of time.

**Comment by antiochp** [comment]
@yeastplume what kind of time are we talking about for `UserTesting` mode to find the genesis block (say on a reasonably fast laptop like a MacBook Pro)? Is this a few minutes or significantly longer than that?

**Comment by yeastplume** [comment]
At the moment, it's instant, because the genesis block data is the same every time, and I've seeded the right nonce into https://github.com/ignopeverell/grin/blob/900c52424d1ef5825a2b343ed53785c05b354525/core/src/global.rs#L106

However, the genesis block should eventually be modifiable with the correct time/date/newspaper headline, so if mining from scratch with the internal miner, cuckoo 16 should take something on the order of a few minutes. Cuckoo 30, however, will be unworkable, it will take days to generate the genesis block. In my own fork (which I haven't PRed yet,) I've pre-seeded this with a GPU mined solution in global.rs.

I'm going to propose some refactoring for a long-term solution in another issue... I'll describe how to address this there and we can probably close this one.

**Comment by yeastplume** [comment]
Solved now, genesis block can be mined with configured miner and works in whatever mode is configured
